// itrf/src/components/ConsentModal.vue
<template>
  <div ref="modal">
    <div class="modal fade show"
        tabindex="-1"
        role="dialog">
      <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h2 class="modal-title">Information collection notice</h2>
          </div>
          <div class="modal-body">
            <p><b>Keep your personal information secure - especially when using a shared device like a computer at a library, school or café.</b> To delete any information that was entered, either complete the application and submit it or, if you don't finish, close the web browser.</p>
            <p><b>Need to take a break and come back later?</b> The data you enter on this form is saved locally to the computer or device you are using until you close the web browser or submit your application.</p>
            <p class="mb-4">Personal information is collected under the authority of the <em>Medicare Protection Act</em> and section 26 (a), (c) and (e) of the <em>Freedom of Information and Protection of Privacy Act</em> for the purposes of administration of the Medical Services Plan. If you have any questions about the collection and use of your personal information, please contact <a href="https://www2.gov.bc.ca/gov/content/health/about-bc-s-health-care-system/partners/health-insurance-bc" target="_blank">Health Insurance BC</a>.</p>
            <Captcha v-if="!isCaptchaValid"
                    :apiBasePath="captchaAPIBasePath"
                    :nonce="applicationUuid"
                    @captchaLoaded="handleCaptchaLoaded()"
                    @captchaVerified="handleCaptchaVerified($event)" />
            <div v-if="isCaptchaValid"
                class="text-success">Captcha successfully verified.</div>
            <div class="mt-3">
              <input type="checkbox"
                    data-cy="consentCheckbox"
                    id="is-terms-accepted"
                    class="d-inline"
                    v-model="isTermsAccepted" />
              <label for="is-terms-accepted"
                    class="mt-3 ml-2 d-inline"><b>I have read and understand this information</b></label>
            </div>
            
          </div>
          <div class="modal-footer justify-content-center">
            <Button label="Continue"
                    cypressId="consentContinue"
                    @click="closeModal()"
                    :disabled="!isCaptchaValid || !isTermsAccepted"/>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Button from "./Button.vue";
import Captcha from './Captcha.vue';

export default {
  name: "ConsentModal",
  components: {
    Button,
    Captcha,
  },
  props: {
    applicationUuid: {
      type: String,
      default: '',
      required: true,
    },
  },
  data: () => {
    return {
      focusableEls: [],
      focusedEl: null,
      captchaAPIBasePath: '/itrf/api/captcha',
      isCaptchaValid: false,
      isTermsAccepted: false,
    };
  },
  created() {
    window.addEventListener('keydown', this.handleKeyDown);
    document.body.classList.add('no-scroll');
  },
  destroyed() {
    window.removeEventListener('keydown', this.handleKeyDown);
    document.body.classList.remove('no-scroll');
  },
  mounted() {
    this.focusableEls = this.getFocusableEls();
  },
  methods: {
    getFocusableEls() {
      // Create an array of focusable elements from the contents of the modal
      return Array.from(this.$refs.modal.querySelectorAll('a[href], area[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), button, [tabindex="0"]'));
    },
    handleCaptchaLoaded() {
      this.focusableEls = this.getFocusableEls();
    },
    handleCaptchaVerified(captchaToken) {
      this.$emit('captchaVerified', captchaToken);
      this.isCaptchaValid = true;
      setTimeout(() => {
        this.focusableEls = this.getFocusableEls();
      }, 0);
    },
    closeModal() {
      this.$emit('close', true);
    },
    handleKeyDown(event) {
      // Handle tabbing
      if (event.key === 'Tab') {
        // Prevent usual tabbing, manually set focus
        event.preventDefault();
        if (event.shiftKey) {
          this.handleTabBackwards();
        } else {
          this.handleTab();
        }
      }
    },
    // Move to next focusable element, if at last element, move to first
    handleTab() {
      if (!this.focusedEl && this.focusableEls.length > 0) {
        this.focusedEl = this.focusableEls[0];
        this.focusedEl.focus();
        return;
      }
      const position = this.focusableEls.indexOf(this.focusedEl);
      if (position === this.focusableEls.length - 1) {
        this.focusedEl = this.focusableEls[0];
      } else {
        this.focusedEl = this.focusableEls[position + 1];
      }
      this.focusedEl.focus();
    },
    // Move to next focusable element, if at last element, move to first
    handleTabBackwards() {
      if (!this.focusedEl && this.focusableEls.length > 0) {
        this.focusedEl = this.focusableEls[this.focusableEls.length - 1];
        this.focusedEl.focus();
        return;
      }
      const position = this.focusableEls.indexOf(this.focusedEl);
      if (position === 0) {
        this.focusedEl = this.focusableEls[this.focusableEls.length - 1];
      } else {
        this.focusedEl = this.focusableEls[position - 1];
      }
      this.focusedEl.focus();
    },
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.modal.show {
  display: block;
  background-color: rgba(0, 0, 0, 0.4);
  overflow-y: scroll;
}
.modal-header {
  background: #036;
  color: #FFF;
}
</style>

// fpcare/src/app/modules/core/components/consent-modal/consent-modal.component.ts
import {Component, ViewChild, EventEmitter, Output, OnInit, ElementRef, ChangeDetectorRef} from '@angular/core';
import { Base } from 'moh-common-lib';
import { ModalDirective } from 'ngx-bootstrap/modal';
import {environment} from '../../../../../environments/environment';
import {ApiService} from '../../../../services/api-service.service';
import {growVertical} from '../../../../animations/animations';

@Component({
  selector: 'fpcare-consent-modal',
  templateUrl: './consent-modal.component.html',
  styleUrls: ['./consent-modal.component.scss'],
  animations: [growVertical]
})
export class ConsentModalComponent extends Base implements OnInit {

  public captchaApiBaseUrl;
  public links = environment.links;

  private _agreeCheck: boolean = false;
  private _hasToken = false;

  @ViewChild('informationCollectionModal', { static: true }) public informationCollectionModal: ModalDirective;
  @ViewChild('agree', { static: true }) checkbox: ElementRef<HTMLInputElement>;

  @Output() onConsented = new EventEmitter<boolean>();

  constructor( private apiService: ApiService, private cd: ChangeDetectorRef ) {
    super();
  }

  ngOnInit() {
    this.captchaApiBaseUrl = environment.captchaApiBaseUrl;
  }

  public openModal(): void {
    this.informationCollectionModal.config.keyboard = false;
    this.informationCollectionModal.config.backdrop = true;
    this.informationCollectionModal.config.ignoreBackdropClick = true;
    this.informationCollectionModal.show();
  }

  public closeModal(): void {
    this.informationCollectionModal.hide();
    this.onConsented.emit( this.agreeCheck );
  }

  public modalShown(event){
    //Set focus on the checkbox
    this.checkbox.nativeElement.focus();
  }

  /** Use the UUID as a cryptographic client nonce to avoid replay attacks. */
  get nonce(): string {
    return this.objectId;
  }

  /**
   * Set the agreed flag
   * @param {boolean} val
   */
  set agreeCheck(val: boolean) {
    this._agreeCheck = val;

    if ( !val ) {
      this._hasToken = false;
    }
  }

  /**
   * Retrieve the agreed flag
   * @returns {boolean}
   */
  get agreeCheck(): boolean {
    return this._agreeCheck;
  }

  setToken(token): void {
    this._hasToken = true;
    this.apiService.setCaptchaToken(token);
  }

  canContinue(): boolean {
    return this.agreeCheck && this._hasToken;
  }

}


<div bsModal #informationCollectionModal="bs-modal"
     fpcModalFocus
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-hidden="true"
     (onShown)="modalShown($event)">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header modal-header-primary">
        <h2 class="modal-title pull-left" id="consentModalTitle">Information Collection Notice</h2>
      </div>
      <div class="modal-body">
        <p id='consentModalDesc'>
          Keep your personal information secure - especially when using a shared computer at a library, school or cafe.
          To remove any information you entered, either complete the application and submit it or, if you don't finish,
          close the web browser.
       </p>
        <p>
          Personal information is collected, used, disclosed and provided security in accordance with the British
          Columbia Freedom of Information and Protection of Privacy Act. If you have any questions about the collection
          or use of this information, please contact <a target="_blank"
          href="{{links.HIBC}}">
          Health Insurance BC</a>.
        </p>
        <br>
      </div>

      <div class="d-flex align-items-center p-md-2">
        <span class="checkbox checkbox-success checkbox-inline pl-4 mb-4 mb-md-0">
          <label class='d-inline'>
            <input required aria-required="true" class="btn btn-lg mr-md-2" name='agree' id="agree" type="checkbox" [(ngModel)]="agreeCheck" #agree>
            <strong>I have read and understand this information</strong>
          </label>
        </span>
      </div>
      <div class="mt-2 pl-4" *ngIf="agreeCheck" [@growVertical]>
        <common-captcha [apiBaseUrl]="captchaApiBaseUrl"
                 [nonce]="nonce"
                 (onValidToken)="setToken($event)"
                 [successMessage]="'  '"></common-captcha>
      </div>

      
      <div class="modal-footer">
        <button [disabled]="!canContinue()"
                class="btn btn-block btn-primary pull-left"
                type="submit"
                (click)="closeModal()">Continue</button>
      </div>
    </div>
  </div>
</div>
